<div id="container">
            <!-- zone de connexion -->
            
            <form action="connexionRedacteur.php" method="POST">
                <h1>Connexion</h1>
                
                <label><b>Nom d'utilisateur</b></label>
                <input type="text" placeholder="Entrer le nom d'utilisateur" name="pseudo" required>

                <label><b>Mot de passe</b></label>
                <input type="password" placeholder="Entrer le mot de passe" name="motdepasse" required>

                <input type="submit" id='submit' value='LOGIN' >
            </form>
</div>