<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" 
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" 
        crossorigin="anonymous"/>
        <link rel="stylesheet" href="../../public/ressources/css/header.css">
        <link rel="stylesheet" href="../../public/ressources/css/section.css">
        <link rel="stylesheet" href="../../public/ressources/css/footer.css">
        <title>Blog Malagasy</title>
    </head>
    <body>
        <header>
            <nav class="header-nav">
                <h1>
                    <a href="#accueil" class="active"></a>
                    <img src="../../public/ressources/images/madagascar-flag-button-square-icon-64.png" alt="Drapeau Malagasy"></a>
                </h1>
                <ul>
                    <li class="lienBlanc"><a href="#artisanat">ARTISANAT</a></li>
                    <li class="lienRouge"><a href="#plantes">PLANTES</a></li>
                    <li class="lienVert"><a href="#commentaires">COMMENTAIRES</a></li>
                </ul>
            </nav>
        </header>
        <section id="home">
            <div>
                <span>TITRE DU BLOG EN FRANCAIS ET EN MALAGASY</span>
            </div>
            <div class="content">
                <?php foreach ($articles as $article) : ?>
                    <div>
                        <h2>
                            <?= htmlspecialchars($article['titre']) ?>
                        </h2>
                        <div class="imageAccueil">
                        <a href="afficheArticle.php?id=<?= intval($article['id']) ?>"><img src="../../public/ressources/images/<?= htmlspecialchars($article['urlImage']) ?>"></a>
                        </div>
                        <p>
                            <?= htmlspecialchars($article['resume']) ?>
                        </p>
                        <p>
                            Rédigé le : <?= htmlspecialchars($article['dateParution']) ?> par : <?= htmlspecialchars($article['pseudo']) ?>
                        </p>
                    </div>
                <?php endforeach ?>
            </div>
        </section>
        <footer>
            <div>
                <i class="fab fa-facebook-square"></i>
                <i class="fab fa-twitter-square"></i>
                <i class="fab fa-instagram"></i>
            </div>
            <div>
                <p><i class="far fa-copyright"></i> Copyright</p>
            </div>
        </footer>
    </body>
</html>