<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="../../public/ressources/css/style.css">

    <title>Blog pour Madagascar</title>
</head>
<body>
    <header>
        <h1></h1>
        <nav>
            <ul>
                <li><a href="#home" class="active">ACCUEIL</a></li>
                <li><a href="#ourWork">ARTISANAT</a></li>
                <li><a href="#medicinalplants">PLANTES</a></li>
                <li><a href="#contact">CONTACTS</a></li>
            </ul>
        </nav>
    </header>
    <section id="home">
        <p>Le savoir faire Malagasy <br />La médecine traditionnelle Malagasy</p>
        <div>Vos commentaires</div>
    </section>

    
</body>
</html>