<header>
    <nav class="header-nav">
        <h1>
            <a href="./" class="active">
            <img src="../../public/ressources/images/madagascar-flag-button-square-icon-64.png" alt="Drapeau Malagasy"></a>
        </h1>
        <ul>
            <li class="lienBlanc"><a href="#artisanat">ARTISANAT</a></li>
            <li class="lienRouge"><a href="#plantes">PLANTES</a></li>
            <li class="lienVert"><a href="#commentaires">COMMENTAIRES</a></li>
        </ul>
    </nav>
</header>
